services:
  - type: web
    name: link-shortener-api
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: link-shortener-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: link-shortener-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"

  - type: pserv
    name: link-shortener-db
    plan: free
    envVars:
      - key: POSTGRES_USER
        value: user
      - key: POSTGRES_DB
        value: linkdb
      - key: POSTGRES_PASSWORD
        generateValue: true
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

  - type: redis
    name: link-shortener-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
