services:
  - type: web
    name: link-shortener-api
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: link-shortener-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: link-shortener-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"

  - type: pserv
    name: link-shortener-db
    plan: free
    databaseName: linkdb
    user: user

  - type: redis
    name: link-shortener-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
